import { defineField, defineType } from 'sanity';

export const legislationUpdateType = defineType({
  name: 'legislationUpdate',
  title: 'Legislation Update',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'legislationType',
      title: 'Legislation Type',
      type: 'string',
      options: {
        list: [
          { title: 'Criminal Code Amendment', value: 'criminal_code' },
          { title: 'Firearms Act', value: 'firearms_act' },
          { title: 'Charter of Rights', value: 'charter' },
          { title: 'Provincial Regulation', value: 'provincial' },
          { title: 'Federal Regulation', value: 'federal_reg' },
          { title: 'Court Rule Change', value: 'court_rule' },
          { title: 'Practice Direction', value: 'practice_direction' },
        ],
      },
    }),
    defineField({
      name: 'source',
      title: 'Source',
      type: 'string',
      description: 'e.g., Justice Canada, Ontario Courts',
    }),
    defineField({
      name: 'sourceUrl',
      title: 'Source URL',
      type: 'url',
    }),
    defineField({
      name: 'effectiveDate',
      title: 'Effective Date',
      type: 'date',
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
    }),
    defineField({
      name: 'fullText',
      title: 'Full Text',
      type: 'array',
      of: [{ type: 'block' }],
    }),
    defineField({
      name: 'aiSummary',
      title: 'AI Layman Summary',
      type: 'text',
      description: 'Plain-language summary generated by AI',
    }),
    defineField({
      name: 'impactAreas',
      title: 'Impact Areas',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'Firearm Classification', value: 'firearm_class' },
          { title: 'Storage Requirements', value: 'storage' },
          { title: 'Transportation Rules', value: 'transport' },
          { title: 'Licensing', value: 'licensing' },
          { title: 'Search and Seizure', value: 'search' },
          { title: 'Sentencing', value: 'sentencing' },
          { title: 'Bail', value: 'bail' },
          { title: 'Disclosure', value: 'disclosure' },
        ],
      },
    }),
    defineField({
      name: 'isBreakingChange',
      title: 'Breaking Change',
      type: 'boolean',
      description: 'Significantly impacts existing practices',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      legislationType: 'legislationType',
      effectiveDate: 'effectiveDate',
      isBreaking: 'isBreakingChange',
    },
    prepare({ title, legislationType, effectiveDate, isBreaking }) {
      return {
        title: `${isBreaking ? '[BREAKING] ' : ''}${title || 'Untitled Update'}`,
        subtitle: `${legislationType || 'Unknown'} - Effective: ${effectiveDate || 'TBD'}`,
      };
    },
  },
});
